# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text=b'The actual contact of the person e.g test@mail.com, 07XXYYYZZZ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'A short name, preferably 6 characters long, representing a certain type of contact e.g EMAIL', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text=b'A brief description of the contact type.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(help_text=b'The type of contact that the given contact is e.g email or phone number', on_delete=django.db.models.deletion.PROTECT, to='common.ContactType'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('contact', 'contact_type')]),
        ),
    ]
