# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='author_name', max_length=255),
            preserve_default=False,
        ),
    ]
