# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutuspage_journalpage_membershippage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='mobile_contact',
            field=models.CharField(default=254, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='signup_link',
            field=models.URLField(blank=True),
        ),
    ]
